//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYNHAHANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apdungcho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apdungcho()
        {
            this.Makhuyenmais = new HashSet<Makhuyenmai>();
        }
    
        public string Áp_dụng_cho { get; set; }
        public string Tên_loại_áp_dụng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makhuyenmai> Makhuyenmais { get; set; }
    }
}
