//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYNHAHANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donhang1()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
        public string Mã_ĐH { get; set; }
        public string Tên_khách_hàng { get; set; }
        public string Địa_chỉ_ { get; set; }
        public string SĐT { get; set; }
        public System.DateTime Ngày_đặt { get; set; }
        public string Mã_khuyến_mãi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Makhuyenmai Makhuyenmai { get; set; }
    }
}
